typing is part of standard library from python3.6 (gives errors on python3.7) (#1638)
* typing is part of standard library from python3.6
installing it on python3.7 causes AttributeError: type object 'Callable' has no attribute '_abc_registry'
refers #1457 and python/typing/issues/573

* remove typing backport because is part of python3.6 natively and allennlp requires python3.6