typing is part of standard library from python3.6 installing it on python3.7 causes AttributeError: type object 'Callable' has no attribute '_abc_registry' refers #1457 and python/typing/issues/573